In [1]:
import torch
import numpy as np

In [7]:
data = [[[1, 2, 3],[3, 4, 5]], [[-1, 2, 3],[-3, 4, 5]]]
data = torch.tensor(data)

In [45]:
data1 = torch.tensor([[1,2],[3,4]], dtype=float)

In [24]:
data1[torch.tensor([[True, True], [False, True]])] = np.nan

RuntimeError: value cannot be converted to type int64_t without overflow: nan

In [26]:
mask = torch.rand([2, 2]) < 0.2

In [46]:
data1.dtype

torch.float64

In [32]:
data1[mask] = np.nan

RuntimeError: value cannot be converted to type int64_t without overflow: nan

In [35]:
data1.dtype

torch.int64

In [7]:
data2_np = np.array(data2)

In [23]:
data = torch.tensor(data2)

In [15]:
torch.randn((2,3,))

tensor([[ 2.0326,  0.2747,  1.1650],
        [-0.1172,  0.4400, -0.1588]])

In [17]:
data2_torch.shape

torch.Size([2, 2, 2])

In [18]:
torch.cuda.is_available()

False

In [27]:
data

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [38]:
data[:, :, 1]

tensor([[2, 4],
        [6, 8]])

In [78]:
d1 = torch.randn([2,3,4])
d2 = torch.randn([3,4,5])

In [80]:
torch.tensordot(d1, d2, dims=2)

tensor([[ 1.1570,  3.6056, -9.4272,  5.8703, -2.8752],
        [-0.1765, -0.4589, -0.9280,  0.0277, -0.7138]])

In [83]:
torch.tensordot(d1, d2, dims=[[1], [0]]).shape

torch.Size([2, 4, 4, 5])

In [85]:
d1.sum().item()

5.190619468688965

In [73]:
torch.matmul(d1, d2)

RuntimeError: size mismatch, got 2, 2x2,3

In [26]:
a = torch.tensor([5,4], dtype=float, requires_grad = True)

In [25]:
b = torch.tensor([3,4], dtype=float, requires_grad = False)

In [51]:
y = a ** 2 + 5 * b

In [52]:
z = y.mean()

In [53]:
z.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [30]:
a.grad

tensor([5., 4.], dtype=torch.float64)

In [31]:
b.grad


In [32]:
from torch.autograd import Variable

In [34]:
av = Variable(a)
bv = Variable(b, requires_grad=True)

In [41]:
yv = av ** 2 + 5 * bv

In [42]:
zv = yv.mean()

In [43]:
zv.backward()

In [44]:
av.grad

In [45]:
bv.grad

tensor([2.5000, 2.5000], dtype=torch.float64)

In [49]:
a.requires_grad = False

In [50]:
a

tensor([5., 4.], dtype=torch.float64)